var sub = {
    art: {
        label: 'アート',
        value: 'アート',
        engName: 'art',
        parentDir: 'topic',
    },
    baseball: {
        label: '野球',
        value: '野球',
        engName: 'baseball',
        parentDir: 'topic',
    },
    beauty: {
        label: '美容',
        value: '美容',
        engName: 'beauty',
        parentDir: 'topic',
    },
    business: {
        label: 'ビジネス',
        value: 'ビジネス',
        engName: 'business',
        parentDir: 'topic',
    },
    career: {
        label: 'キャリア',
        value: 'キャリア',
        engName: 'career',
        parentDir: 'topic',
    },
    childraising: {
        label: '育児',
        value: '育児',
        engName: 'childraising',
        parentDir: 'topic',
    },
    column: {
        label: 'コラム・エッセイ',
        value: 'コラム・エッセイ',
        engName: 'column',
        parentDir: 'topic',
    },
    creation: {
        label: '創作',
        value: '創作',
        engName: 'creation',
        parentDir: 'topic',
    },
    design: {
        label: 'デザイン',
        value: 'デザイン',
        engName: 'design',
        parentDir: 'topic',
    },
    education: {
        label: '教育',
        value: '教育',
        engName: 'education',
        parentDir: 'topic',
    },
    entertainment: {
        label: '芸能',
        value: '芸能',
        engName: 'entertainment',
        parentDir: 'topic',
    },
    fashion: {
        label: 'ファッション',
        value: 'ファッション',
        engName: 'fashion',
        parentDir: 'topic',
    },
    gadget: {
        label: 'ガジェット',
        value: 'ガジェット',
        engName: 'gadget',
        parentDir: 'topic',
    },
    gourmet: {
        label: 'フード',
        value: 'フード',
        engName: 'gourmet',
        parentDir: 'topic',
    },
    health: {
        label: '健康',
        value: '健康',
        engName: 'health',
        parentDir: 'topic',
    },
    humanities: {
        label: '人文学',
        value: '人文学',
        engName: 'humanities',
        parentDir: 'topic',
    },
    it: {
        label: 'IT',
        value: 'IT',
        engName: 'it',
        parentDir: 'topic',
    },
    economy: {
        label: '経済・投資',
        value: '経済・投資',
        engName: 'economy',
        parentDir: 'topic',
    },
    lifestyle: {
        label: 'ライフスタイル',
        value: 'ライフスタイル',
        engName: 'lifestyle',
        parentDir: 'topic',
    },
    livelihood: {
        label: '家庭',
        value: '家庭',
        engName: 'livelihood',
        parentDir: 'topic',
    },
    local: {
        label: '地域・行政',
        value: '地域・行政',
        engName: 'local',
        parentDir: 'topic',
    },
    love: {
        label: '恋愛',
        value: '恋愛',
        engName: 'love',
        parentDir: 'topic',
    },
    movie: {
        label: '映画・ドラマ',
        value: '映画・ドラマ',
        engName: 'movie',
        parentDir: 'topic',
    },
    music: {
        label: '音楽',
        value: '音楽',
        engName: 'music',
        parentDir: 'topic',
    },
    novel: {
        label: '小説',
        value: '小説',
        engName: 'novel',
        parentDir: 'topic',
    },
    pet: {
        label: 'ペット',
        value: 'ペット',
        engName: 'pet',
        parentDir: 'topic',
    },
    radio: {
        label: 'ラジオ',
        value: 'ラジオ',
        engName: 'radio',
        parentDir: 'topic',
    },
    reading: {
        label: '読書',
        value: '読書',
        engName: 'reading',
        parentDir: 'topic',
    },
    science: {
        label: 'サイエンス',
        value: 'サイエンス',
        engName: 'science',
        parentDir: 'topic',
    },
    shopping: {
        label: 'ショッピング',
        value: 'ショッピング',
        engName: 'shopping',
        parentDir: 'topic',
    },
    soccer: {
        label: 'サッカー',
        value: 'サッカー',
        engName: 'soccer',
        parentDir: 'topic',
    },
    stage: {
        label: '舞台',
        value: '舞台',
        engName: 'stage',
        parentDir: 'topic',
    },
    manga: {
        label: 'マンガ',
        value: 'マンガ',
        engName: 'manga',
        parentDir: 'topic',
    },
    photo: {
        label: '写真',
        value: '写真',
        engName: 'photo',
        parentDir: 'topic',
    },
    tech: {
        label: 'テクノロジー',
        value: 'テクノロジー',
        engName: 'tech',
        parentDir: 'topic',
    },
    sports: {
        label: 'スポーツ',
        value: 'スポーツ',
        engName: 'sports',
        parentDir: 'topic',
    },
    game: {
        label: 'ゲーム',
        value: 'ゲーム',
        engName: 'game',
        parentDir: 'topic',
    },
    travel: {
        label: '旅行・おでかけ',
        value: '旅行・おでかけ',
        engName: 'travel',
        parentDir: 'topic',
    },
    ai: {
        label: 'AI',
        value: 'AI',
        engName: 'ai',
        parentDir: 'topic',
    },
    vehicle: {
        label: '乗り物',
        value: '乗り物',
        engName: 'vehicle',
        parentDir: 'topic',
    },
    qualification: {
        label: '資格',
        value: '資格',
        engName: 'qualification',
        parentDir: 'topic',
    },
    mahjong: {
        label: '麻雀',
        value: '麻雀',
        engName: 'mahjong',
        parentDir: 'topic',
    },
    outdoor: {
        label: 'アウトドア',
        value: 'アウトドア',
        engName: 'outdoor',
        parentDir: 'topic',
    },
    '3d': {
        label: '3DCG',
        value: '3DCG',
        engName: '3d',
        parentDir: 'topic',
    },
    modelmold: {
        label: '造形',
        value: '造形',
        engName: 'modelmold',
        parentDir: 'topic',
    },
    vr: {
        label: 'VR・AR',
        value: 'VR・AR',
        engName: 'vr',
        parentDir: 'topic',
    },
    vtuber: {
        label: 'Vtuber',
        value: 'Vtuber',
        engName: 'vtuber',
        parentDir: 'topic',
    },
    handicraft: {
        label: '手芸',
        value: '手芸',
        engName: 'handicraft',
        parentDir: 'topic',
    },
    diy: {
        label: 'DIY',
        value: 'DIY',
        engName: 'diy',
        parentDir: 'topic',
    },
    toyhobby: {
        label: 'ホビー・玩具',
        value: 'ホビー・玩具',
        engName: 'toyhobby',
        parentDir: 'topic',
    },
    anime: {
        label: 'アニメ・特撮',
        value: 'アニメ・特撮',
        engName: 'anime',
        parentDir: 'topic',
    },
    programming: {
        label: 'プログラミング',
        value: 'プログラミング',
        engName: 'programming',
        parentDir: 'topic',
    },
    keiba: {
        label: '競馬',
        value: '競馬',
        engName: 'keiba',
        parentDir: 'topic',
    },
};
export const categories=Object.values(sub)
// export const categories = [
//     {
//         id: 1,
//         label: 'くらし',
//         options: [
//             sub.livelihood,
//             sub.gourmet,
//             sub.lifestyle,
//             sub.shopping,
//             sub.childraising,
//             sub.health,
//             sub.travel,
//             sub.pet,
//             sub.column,
//             sub.beauty,
//             sub.fashion,
//             sub.diy,
//             sub.modelmold,
//             sub.handicraft,
//             sub.outdoor,
//         ],
//     },
//     {
//         id: 2,
//         label: 'まなび',
//         options: [sub.education, sub.reading, sub.design, sub.humanities, sub.science, sub.qualification],
//     },
//     {
//         id: 3,
//         label: 'しごと',
//         options: [ sub.design, sub.business, sub.career, sub.it],
//     },
//     {
//         id: 4,
//         label: '社会',
//         options: [sub.local, sub.business, sub.science, sub.humanities, sub.economy],
//     },
//     {
//         id: 5,
//         label: 'エンタメ',
//         options: [
//             sub.manga,
//             sub.entertainment,
//             sub.movie,
//             sub.music,
//             sub.radio,
//             sub.stage,
//             sub.game,
//             sub.sports,
//             sub.baseball,
//             sub.soccer,
//             sub.keiba,
//             sub.mahjong,
//             sub.vtuber,
//             sub.anime,
//         ],
//     },
//     {
//         id: 6,
//         label: 'テクノロジー',
//         options: [sub.tech, sub.science, sub.it, sub.gadget, sub.ai, sub.programming, sub.vr, sub['3d']],
//     },
//     {
//         id: 7,
//         label: 'カルチャー',
//         options: [
//             sub.manga,
//             sub.love,
//             sub.art,
//             sub.reading,
//             sub.entertainment,
//             sub.creation,
//             sub.novel,
//             sub.photo,
//             sub.design,
//             sub.outdoor,
//             sub.vehicle,
//             sub.toyhobby,
//         ],
//     },
// ];
